robot1:
  slam_toolbox:
    ros__parameters:
      use_sim_time: true
      odom_frame: robot1/odom
      map_frame: robot1/map
      base_frame: robot1/base_footprint
      scan_topic: /robot1/scan
      mode: mapping
      resolution: 0.05
      max_laser_range: 10.0
      minimum_travel_distance: 0.2
      minimum_travel_heading: 0.15
      map_update_interval: 2.0
      loop_search_maximum_distance: 3.0
      do_loop_closing: true
      transform_timeout: 1.0
      tf_buffer_duration: 60.0
      stack_size_to_use: 40000000
      transform_publish_period: 0.05
      scan_buffer_size: 10
      scan_buffer_maximum_scan_distance: 10.0

robot2:
  slam_toolbox:
    ros__parameters:
      use_sim_time: true
      odom_frame: robot2/odom
      map_frame: robot2/map
      base_frame: robot2/base_footprint
      scan_topic: /robot2/scan
      mode: mapping
      resolution: 0.05
      max_laser_range: 10.0
      minimum_travel_distance: 0.2
      minimum_travel_heading: 0.15
      map_update_interval: 2.0
      loop_search_maximum_distance: 3.0
      do_loop_closing: true
      transform_timeout: 1.0
      tf_buffer_duration: 60.0
      stack_size_to_use: 40000000
      transform_publish_period: 0.05
      scan_buffer_size: 10
      scan_buffer_maximum_scan_distance: 10.0